name: Maven Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: sentrysoftware/workflows/.github/workflows/maven-build.yml@main
    with:
      jdkVersion: "17"
      nodeVersion: "14.x"
