name: Maven Build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Build in debug mode and open SSH session to workspace
        required: false
        default: false
        
jobs:
  build:
    uses: sentrysoftware/workflows/.github/workflows/maven-build.yml@main
    with:
      jdkVersion: "17"
      nodeVersion: "20.x"
      debug: ${{ inputs.debug }}
